[Unit]
Description="CN"
Documentation="192.168.1.1"

[Socket]
ExecStartPre="/usr/bin/sleep 5"
ListenStream="31972"
Accept = false
ReceiveBuffer = 4096
SendBuffer = 4096
PassPacketInfo = false
PassCredentials = false
PassSecurity = true
SocketMode=600

[Install]
WantedBy="dbus.service"
