[package]
name = "devmaster"
version = "0.1.0"
edition = "2021"
default-run = "devmaster"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "devmaster"
path = "src/bin/devmaster.rs"

[[bin]]
name = "devctl"
path = "src/bin/devctl.rs"

[lib]
name = "libdevmaster"
path = "src/lib.rs"

[dependencies]
# internal libraries
device = { path = "../../libs/device" }
event = { path = "../../libs/event" }
basic = { path = "../../libs/basic" }

# third libraries
libc = "0.2.*"
bitflags = "1.3.2"
thiserror = "1.0"
netlink-sys = "0.8.3"
nix = "0.24"
log = "0.4"
snafu = "0.7"
clap = { version = "3.1.8", features = ["derive"] }
