[package]
name = "process1"
version = "0.1.0"
authors = ["Shinwell Hu <huxinwei@huawei.com>"]
edition = "2018"

license = "MulanPSL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = { version = "0.3.7", features = ["extended-siginfo"] }

