[workspace]
members = [
  "libevent",
  "init",
  "process1",
  "sysmonitor",
  "systemd",
  "libutils",
  "libproc_macro_utils",
  "tests",
  "components/service",
  "components/socket",
  "components/target",
  "components/mount",
  "utilities/random_seed",
  "utilities/rc-local-generator",
  "utilities/fstab",
]
