[package]
name = "target"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
crate-type = ["dylib"]
name = "target"

[dependencies]
libutils = { path = "../../libs/libutils" }
proc_macro_utils = { path = "../../libs/libproc_macro_utils" }
sysmaster = {path = "../../"}
nix = "0.24"
log = "0.4"
serde = "1.0.130"
once_cell = { version = "1.5.2"}
