[package]
name = "utils"
version = "0.1.0"
authors = ["overweight <hexiaowen@huawei.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]
name = "utils"

[dependencies]
toml = "0.5.8"
serde_derive = "1.0.130"
serde = "1.0.130"
