[package]
name = "random_seed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2" }
log = "0.4"
xattr = "0.2.3"
nix = "0.23.0"
#cargo-tarpaulin = "0.20.1"