[package]
name = "sysmonitor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sysmonitor"

[dependencies]
log = "0.4"
nix = "0.23.0"
procfs = "0.12.0"
toml = "0.5.8"
serde = "1.0.130"
serde_derive = "1.0.130"