[package]
name = "init"
version = "0.1.0"
authors = ["overweight <hexiaowen@huawei.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal-hook = { version = "0.3.7", features = ["extended-siginfo"] }
signal-hook-registry = "*"
utils = { path = "../utils" }
libc = { version = "^0.2" }
