[Unit]
Description="CN"
Documentation="192.168.1.1"


[Service]
Type="Simple"
ExecCondition="/usr/bin/sleep 5"
ExecStart="/bin/echo 'test'"
ExecStop="/bin/kill $MAINPID"
WatchdogUSec=10

[Install]
WantedBy="dbus.service"
