[package]
name = "fstab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fstab"
path = "src/fstab.rs"

[dependencies]
inotify = "0.10"
nix = "0.23.0"
libc = "0.2.0"
libmount = "0.1.15"
log = "0.4"